### ISSUE TITLE
 Sorry, but "public_html" is not empty, please backup your data before continue.

### ISSUE THREAD

**Issue by ashbryant** [lbngoc/php-docker-dev#1]
Hi,

This looks like an interesting fork of 10up's version. However, I have fallen at the first hurdle. When trying to run npm run setup-bedrock or npm run setup-wordpress produces this error  

Sorry, but "public_html" is not empty, please backup your data before continue.

even if the folder is empty. Any advice?

Thanks 
Ash
Sorry, but "public_html" is not empty, please backup your data before continue.

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup-wordpress"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! php-docker-dev@1.0.0 setup-wordpress: `docker-compose run --rm --user "1000:1000" phpfpm /docker/bin/setup-wp.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the php-docker-dev@1.0.0 setup-wordpress script 'docker-compose run --rm --user "1000:1000" phpfpm /docker/bin/setup-wp.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the php-docker-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker-compose run --rm --user "1000:1000" phpfpm /docker/bin/setup-wp.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs php-docker-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls php-docker-dev
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ash/Sites/php-docker-dev-master/npm-debug.log

**Comment by lbngoc** [comment]
Hi @ashbryant ,

Thanks for your report!
It's my fault from [previous commit](https://github.com/lbngoc/php-docker-dev/commit/7128c6bc455b3a47984ef9d122fa0a02f9e7c4d0#diff-a606c49d958dc8a9194cc68c295d6608)

This issue was fixed with my latest commit, please update the source code and try again.
Let me know if you have any issues.

**Comment by ashbryant** [comment]
Hi

Sorry for the delay in getting back to you.

New issue 

ERROR: The Compose file is invalid because:
Service elasticsearch has neither an image nor a build context specified. At least one must be provided.

**Comment by ashbryant** [comment]
Yep all fixed. Thanks
