### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by ashbryant** [lbngoc/php-docker-dev#2]
More of a question than an issue. Is there any way of speeding things up? I find the same issue with the original repo from 10up that once you start using it way from the initial install the whole install becomes very slow.

I'm using docker for Mac, Macbook Pro 2015, 16GB Ram (DDR3), 2.5 GHz Intel Core i7

**Comment by lbngoc** [comment]
@ashbryant 

The speed issue is came from "composer" (https://github.com/composer/composer/issues/3156)
In the next version, I think I will use "git" and some native *NIX commands to improve the speed of setup scripts.

**Comment by ashbryant** [comment]
Sorry, I was referring to the running of WordPress itself. After the install and the 'day to day' use of WP ( adding plugins and content etc ) it seems slow.

**Comment by ashbryant** [comment]
I think the speed issue came from Docker on a mac.
