### ISSUE TITLE
Question: How do you add imagemagick?

### ISSUE THREAD

**Issue by ashbryant** [lbngoc/php-docker-dev#3]
Hi,

Sorry, I'm still a noob at this. But how would you add imagemagick to the stack?

**Comment by lbngoc** [comment]
I guess that you need to install Imagick extension (http://php.net/manual/en/book.imagick.php)
I do not know how are cons and prods of Imagick but I see that GD Library (http://php.net/manual/en/book.image.php) is popular than it, and GD library is used on almost platform such as Wordpress, Magento... 
If you really like to use Imagick, just create new Dockerfile for phpfpm service like this:

Create new file `config/php-fpm/Dockerfile`
```
FROM 10up/phpfpm
RUN apt-get update && apt-get install -y \
  git libmagick++-dev \
  --no-install-recommends && rm -r /var/lib/apt/lists/* && \
  git clone https://github.com/mkoppanen/imagick.git && \
  cd imagick && git checkout phpseven && phpize && ./configure && \
  make && make install && \
  docker-php-ext-enable imagick && \
  cd ../ && rm -rf imagick
```
Edit `docker-compose.yml`
```
  ...
  phpfpm:
    #image: 10up/phpfpm
    build: ./config/php-fpm
 ...
```
Then rebuild php-fpm service
`docker-compose down php-fpm && docker-compose up php-fpm`
