### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by ashbryant** [lbngoc/php-docker-dev#4]
Hi 
I love what you have here but I was just wondering if you had plans to keep it up to date with the original branch here https://github.com/10up/wp-local-docker ?

**Comment by lbngoc** [comment]
Hi @ashbryant ,
Thanks for your interesting with my work!
Currently I spend most time with WordPress development and create a new Repo here for initializing new project: http://github.com/lbngoc/sage-8-webpack
Could you take a look this Repo for reference?
